name: Update Dockerfiles

on:
  push:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Update Dockerfiles
      run: ./update.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
